### ISSUE TITLE
Главный заголовок

### ISSUE THREAD

**Issue by Morfey216** [WEVI0Z/Technomart#10]
Если подумать, то это не просто параграф, и уж точно не слоган:
https://github.com/WEVI0Z/Technomart/blob/175f1f01561b939baba2b8a8a28e681c03e3b2f6/index.html#L36-L40

Это главный заголовок всего сайта, т.е. заголовок первого уровня

**Comment by WEVI0Z** [comment]
Сделал заголовком

**Comment by Morfey216** [comment]
А зачем оставил ему такой странный класс?
https://github.com/WEVI0Z/Technomart/blob/7586ca2cd0137db33dc7154a863dfa80c4418ded/index.html#L30

Далее - на странице оставляем только один заголовок первого уровня! В связи с этим класс для h1 можно вообще не прописывать.
И да - эту фигню надо убрать:
https://github.com/WEVI0Z/Technomart/blob/7586ca2cd0137db33dc7154a863dfa80c4418ded/index.html#L85

**Comment by WEVI0Z** [comment]
Убрал класс и второй заголовок
