### ISSUE TITLE
Карточка товара

### ISSUE THREAD

**Issue by Morfey216** [WEVI0Z/Technomart#11]
Тут будет сразу несколько пунктов, проще объединить в одно описание...
Пример карточки
https://github.com/WEVI0Z/Technomart/blob/175f1f01561b939baba2b8a8a28e681c03e3b2f6/index.html#L165-L170

А теперь по пунктам... Смотрим скрин: http://joxi.ru/nAy4NExTwWN0j2
1. У контентных изображений нужно прописывать размеры
2. Это Заголовок товара!
3. Вопрос нейминга, например discount подойдет лучше
4. Что здесь делает br ???
5. Здесь должна быть ссылка

**Comment by WEVI0Z** [comment]
Насчет 5-го пункта, там, опираясь на styleguide, вся карточка должна быть ссылкой, ну как я вижу. Там так и прописано, что при наведении на карточку, появляются кнопки и появляется вокруг карточки тень.
https://prnt.sc/vyhsmi

**Comment by WEVI0Z** [comment]
Все исправил, но ссылку пока что сделал для всей карточки, а не для ссылки

**Comment by Morfey216** [comment]
1. Последовательность атрибутов
https://github.com/WEVI0Z/Technomart/blob/7586ca2cd0137db33dc7154a863dfa80c4418ded/index.html#L155
вроде как не ошибка, но рекомендую такой порядок: src, width, height, alt - так пишут чаще всего и, соответственно, становится привычнее читать код

2. Скидка...
https://github.com/WEVI0Z/Technomart/blob/7586ca2cd0137db33dc7154a863dfa80c4418ded/index.html#L211-L212
Прописывай дискаунт для всех товаров, только там, где нет скидки, оставляй его пустым

3. Не очень разумно в данном макете всю карточку делать ссылкой, тем более, что кнопка с ценой явно видна... Работать должно так: https://gyazo.com/b888323b04221dd6dee6f48de5faaebb

**Comment by WEVI0Z** [comment]
Исправил, но не уверен насчет того, нужна ли здесь обертка <div>. Можно было бы разграничить два блока:
https://prnt.sc/w1wbyv

**Comment by Morfey216** [comment]
По оберткам - пока всё нормально. Однако есть другой момент:
https://github.com/WEVI0Z/Technomart/blob/b1b9e77e58e0b2bd6fe1cd56992f068d31ebcd92/index.html#L188-L197
Здесь внутри дива 2 ссылки, список не нужен!
И убери ты этот класс visually-hidden - он предназначен совершенно для других целей!

**Comment by WEVI0Z** [comment]
Исправил

**Comment by Morfey216** [comment]
Одно правишь, другое "косячишь"...
https://github.com/WEVI0Z/Technomart/blob/2b2385f374a04f194d024a38a4d8e54dd440a2e6/index.html#L159-L163
зачем на `div `какой-то `hidden `повесил? Дай нормальный класс, вроде `action-choice`, чтобы было понятно, что за блок такой...
И на элемент списка тоже рекомендую класс добавить

**Comment by WEVI0Z** [comment]
Классы добавил
