### ISSUE TITLE
Метка new

### ISSUE THREAD

**Issue by Morfey216** [WEVI0Z/Technomart#12]
https://github.com/WEVI0Z/Technomart/blob/175f1f01561b939baba2b8a8a28e681c03e3b2f6/index.html#L173
Метку "new" лучше реализовать отдельным блоком (через div), добавив картинку через стили, т.к. это не контентное изображение.

**Comment by WEVI0Z** [comment]
Я исправил, но мне все равно кажется, что эта плашка - контентное изображение, так как нигде о том, что предложение/товар новый на сайте, и, соответственно, пользователь теряет важную для него информацию, если эту плашку убрать, но я могу ошибаться

**Comment by Morfey216** [comment]
Тут есть пара моментов...
1. Сегодня товар новый, а завтра уже перестанет быть таковым, и при этом свойства самого товара не изменятся. Таким образом, метка new описывает состояние товара
2. Метки могут меняться или быть различными у различных товаров. Например "новый", "скидка", "акция" и т.д. Удобнее управлять такими метками с помощью назначения классов, а не меняя изображение в разметке
3. С точки зрения доступности тоже будет всё ОК, если сделать так, как я писал выше, - в разметку включить отдельный блок

Нет, не так
https://github.com/WEVI0Z/Technomart/blob/7586ca2cd0137db33dc7154a863dfa80c4418ded/index.html#L210

Сделай так:
`<div class="flag flag-new"><span class="visually-hidden">Новинка</span></div>`

**Comment by WEVI0Z** [comment]
Понял, исправил

**Comment by Morfey216** [comment]
https://github.com/WEVI0Z/Technomart/blob/b1b9e77e58e0b2bd6fe1cd56992f068d31ebcd92/index.html#L199
Этот элемент лучше разместить в самом начале, не смешивая с разметкой карточки товара!
К тому же так его легко будет добавлять/удалять скриптом, если это понадобится.

**Comment by WEVI0Z** [comment]
Исправил в карточках, только здесь не трогал
![image](https://user-images.githubusercontent.com/43513627/104336405-6dc8b680-5505-11eb-8d44-fced2dc9b8f9.png)

**Comment by Morfey216** [comment]
Угу... т.е. правильно ли я понимаю, что ты внутри ссылки оставил какой-то "левый" блок, который к содержимому ссылки не имеет никакого отношения? 
https://github.com/WEVI0Z/Technomart/blob/2b2385f374a04f194d024a38a4d8e54dd440a2e6/index.html#L88-L92
Исправить...

**Comment by WEVI0Z** [comment]
Я в коммите про блок авторизованного пользователя, исправил эту часть в соответствии с ТЗ, и сделал ссылкой только кнопку, которую можно увидеть на макете, и теперь, как я понимаю, надобности в отделении нет. Сейчас только переместил только саму метку вверх
