### ISSUE TITLE
Блок Популярные производители

### ISSUE THREAD

**Issue by Morfey216** [WEVI0Z/Technomart#13]
https://github.com/WEVI0Z/Technomart/blob/175f1f01561b939baba2b8a8a28e681c03e3b2f6/index.html#L184-L187
1. Ссылкой является вся карточка-логотип (пункт 3.9 Технического Задания) и заголовков там нет.
2. Я не заметил, где в ТЗ прописаны эти адреса ссылок???

**Comment by WEVI0Z** [comment]
Исправил

**Comment by Morfey216** [comment]
https://github.com/WEVI0Z/Technomart/blob/7586ca2cd0137db33dc7154a863dfa80c4418ded/index.html#L222-L224

1. aria-label здесь не нужен, нужная информация содержится в alt
2. снова не прописаны размеры
3. у всех пустых ссылок оставляем заглушку в виде решетки, т.е. `<a href="#">...</a>`

**Comment by WEVI0Z** [comment]
Исправил этот блок
