### ISSUE TITLE
Блок авторизованного пользователя

### ISSUE THREAD

**Issue by Morfey216** [WEVI0Z/Technomart#14]
https://github.com/WEVI0Z/Technomart/blob/175f1f01561b939baba2b8a8a28e681c03e3b2f6/index.html#L54-L61
Помимо возможности залогиниться на странице в разметке должен быть предусмотрен блок авторизованного пользователя. Эти блоки будут переключаться, т.е. в разметке должны быть оба, а виден только один

**Comment by WEVI0Z** [comment]
Исправил, сейчас должно быть правильно сделано

**Comment by Morfey216** [comment]
Это ссылка:
https://github.com/WEVI0Z/Technomart/blob/b1b9e77e58e0b2bd6fe1cd56992f068d31ebcd92/index.html#L44
Читай ТЗ:
3.4. В блоке авторизованного посетителя имя и иконка пользователя являются
ссылкой на профайл, а иконка выхода — на страницу деавторизации.

**Comment by WEVI0Z** [comment]
Исправил

**Comment by Morfey216** [comment]
Давай по порядку...
https://github.com/WEVI0Z/Technomart/blob/2b2385f374a04f194d024a38a4d8e54dd440a2e6/index.html#L43-L48
1. Опять hidden... Ну не нужен он! На стадии разметки не нужно прятать блоки, эта процедура выполняется при стилизации и обычно решается оперированием псевдо-служебных классов.
2. Иконка выхода - не кнопка! ЧИТАЙ ТЗ!!!
3. Две ссылки навигации "Мои заказы" и "Личный кабинет" лучше отделить от управления авторизации

**Comment by WEVI0Z** [comment]
Я прочитал обязательные требования и исправил еще пару моментов, связанных с ТЗ в этом же коммите

**Comment by Morfey216** [comment]
https://github.com/WEVI0Z/Technomart/blob/c4f8e9181a94ff6a59f739669074b15be2aac1aa/index.html#L44-L63

смотрим... у тебя три несвязанных друг с другом блока: div и два списка, причем идут они в странном порядке - зарегистрированный пользователь, не зарегистрированный и снова зарегистрированный. Как ты будешь их переключать?
Должно быть 2 независимых блока: один - для зарегистрированного пользователя, а второй - для незарегистрированного. Только "Мои заказы" и "Личный кабинет" отделить от имени и "Выйти"

**Comment by WEVI0Z** [comment]
Теперь сделал по-другому
