### ISSUE TITLE
Поиск

### ISSUE THREAD

**Issue by Morfey216** [WEVI0Z/Technomart#16]
Раздел поиска тоже надо реализовать через форму
https://github.com/WEVI0Z/Technomart/blob/b1b9e77e58e0b2bd6fe1cd56992f068d31ebcd92/index.html#L17-L19

**Comment by WEVI0Z** [comment]
Вроде как исправил

**Comment by Morfey216** [comment]
ОК, только кое-что поправим... У тега form, как правило, указываем два базовых атрибута: `action` и `method`
https://github.com/WEVI0Z/Technomart/blob/2b2385f374a04f194d024a38a4d8e54dd440a2e6/index.html#L17
Описание атрибутов найдешь сам или дать ссылки?

**Comment by WEVI0Z** [comment]
Добавил атрибут action

**Comment by Morfey216** [comment]
https://github.com/WEVI0Z/Technomart/blob/c4f8e9181a94ff6a59f739669074b15be2aac1aa/index.html#L17

Всё-таки дам ссылки:
http://htmlbook.ru/html/form/action
http://htmlbook.ru/html/form/method

**Comment by WEVI0Z** [comment]
Похоже я перепутал атрибуты, сейчас исправил
