### ISSUE TITLE
Промо-блок "материалы..."

### ISSUE THREAD

**Issue by Morfey216** [WEVI0Z/Technomart#17]
https://github.com/WEVI0Z/Technomart/blob/2b2385f374a04f194d024a38a4d8e54dd440a2e6/index.html#L94-L99

Еще раз повторю: читай внимательно техническое задание. Именно ТЗ является основным документом к выполнению!
Цитирую:
3.6. Промо-блок («материалы», «инструмент», ...): ссылками являются только кнопки.

**Comment by WEVI0Z** [comment]
Я исправил в коммите про блок авторизованного пользователя, так как я сначала прочитал ТЗ, после проблемы с блоком, а потом увидел эту проблему здесь
