### ISSUE TITLE
Промо-Слайдер

### ISSUE THREAD

**Issue by Morfey216** [WEVI0Z/Technomart#18]
1. Элемент "Открыть каталог" присутствует у обоих слайдов, независимо друг от друга. У тебя же эта ссылка вынесена вообще за пределы слайдов
https://github.com/WEVI0Z/Technomart/blob/2b2385f374a04f194d024a38a4d8e54dd440a2e6/index.html#L132

2. параграф:
https://github.com/WEVI0Z/Technomart/blob/2b2385f374a04f194d024a38a4d8e54dd440a2e6/index.html#L127

**Comment by WEVI0Z** [comment]
Я не предусмотрел, что там переход в разные каталоги. Исправил

**Comment by Morfey216** [comment]
Проверь валидацию...
https://github.com/WEVI0Z/Technomart/blob/c4f8e9181a94ff6a59f739669074b15be2aac1aa/index.html#L125

_"Я не предусмотрел, что там переход в разные каталоги"_
Это не разные каталоги. Это - разные слайды
