### ISSUE TITLE
Тег <br>

### ISSUE THREAD

**Issue by Morfey216** [WEVI0Z/Technomart#2]
Использование тега **br** в таких местах является ошибкой
https://github.com/WEVI0Z/Technomart/blob/175f1f01561b939baba2b8a8a28e681c03e3b2f6/index.html#L37-L39

В данном макете есть всего пару мест, где уместен принудительный перенос строки

**Comment by WEVI0Z** [comment]
Пересмотрел все теги <br> и убрал те, которые счел необязательными

**Comment by Morfey216** [comment]
Пока еще не всё убрано, писал здесь (2-й пункт):
https://github.com/WEVI0Z/Technomart/issues/8#issuecomment-742141442

**Comment by WEVI0Z** [comment]
Убрал там, где почта и телефон

**Comment by Morfey216** [comment]
https://github.com/WEVI0Z/Technomart/blob/b1b9e77e58e0b2bd6fe1cd56992f068d31ebcd92/index.html#L372
https://github.com/WEVI0Z/Technomart/blob/b1b9e77e58e0b2bd6fe1cd56992f068d31ebcd92/index.html#L385

**Comment by WEVI0Z** [comment]
Исправлено
