### ISSUE TITLE
Пагинация

### ISSUE THREAD

**Issue by Morfey216** [WEVI0Z/Technomart#20]
Блок перехода по страницам называют пагинацией, соответственно и классы именуют
https://github.com/WEVI0Z/Technomart/blob/2b2385f374a04f194d024a38a4d8e54dd440a2e6/catalog.html#L287-L290

И почему ты решил, что там кнопки?

**Comment by WEVI0Z** [comment]
Классы исправил, только мне очень понятно, что там должно быть вместо кнопок. Я посмотрел примеры реализации, там использовали ссылки, но я не понимаю почему. Я исправил на ссылки, но просто хотелось бы понять, почему
![image](https://user-images.githubusercontent.com/43513627/104854024-bd4c1f80-5915-11eb-94ae-3cd8e3aec854.png)

**Comment by Morfey216** [comment]
```
<ul class="pagination-list">
      <li class="pagination-item pagination-item-current"><a>1</a></li>
      <li class="pagination-item"><a href="#">2</a></li>
      <li class="pagination-item"><a href="#">3</a></li>
      <li class="pagination-item pagination-next"><a href="#">Следующая</a></li>
</ul>
```
А ссылки там потому, что переход по страницам может выполняться через запрос к серверу. Сервер отбирает новые данные из базы и формирует новую страницу, и чтобы понимать, какие именно данные нужны и какую страницу собрть, в запросе передаются параметры. Ссылка умеет это делать, а кнопка - нет.

**Comment by WEVI0Z** [comment]
Понял, спасибо

**Comment by Morfey216** [comment]
Атрибут href должен присутствовать у всех ссылок, кроме текущей страницы
https://github.com/WEVI0Z/Technomart/blob/4c55a382833acc1ff0d34eeef0801721fdd4dd30/catalog.html#L294

**Comment by WEVI0Z** [comment]
Что означает кроме текущей страницы, вы про лого, которое переносит на эту же страницу? Тут не очень понял.

А так исправил все ссылки

**Comment by Morfey216** [comment]
> Что означает кроме текущей страницы, вы про лого, которое переносит на эту же страницу?

Нет, я не про лого... Я про этот код:
https://github.com/WEVI0Z/Technomart/blob/9dbd916f772970c93ab3fb06fb40f600c8c0e78b/catalog.html#L290-L292

Чуть выше я дал тебе полный код блока пагинации https://github.com/WEVI0Z/Technomart/issues/20#issuecomment-763813038
Если ты внимательно посмотришь, то у ссылки, которая является текущей на данный момент, атрибута `href` нету. А причина проста - веб сервисы негативно относятся к циклическим ссылкам, т.е. к ссылкам, при клике на которые ты переходишь на ту же страницу. Логотип, если он на главной, тоже попадает под этот пункт

**Comment by WEVI0Z** [comment]
Окей, теперь понял и исправил
