### ISSUE TITLE
Модальное окно

### ISSUE THREAD

**Issue by Morfey216** [WEVI0Z/Technomart#21]
https://github.com/WEVI0Z/Technomart/blob/c4f8e9181a94ff6a59f739669074b15be2aac1aa/catalog.html#L322-L336
Модальные окна, как правило, выносят в конец страницы, после футера, т.к. они являются вспомогательными элементами.

2. Это параграф
https://github.com/WEVI0Z/Technomart/blob/c4f8e9181a94ff6a59f739669074b15be2aac1aa/catalog.html#L325

3. https://github.com/WEVI0Z/Technomart/blob/c4f8e9181a94ff6a59f739669074b15be2aac1aa/catalog.html#L329-L331 - ссылка
4. https://github.com/WEVI0Z/Technomart/blob/c4f8e9181a94ff6a59f739669074b15be2aac1aa/catalog.html#L324-L327
эта кнопка не должна быть в данном блоке

**Comment by WEVI0Z** [comment]
Перенес все модальные окна после футера и исправил остальные пункты

**Comment by Morfey216** [comment]
Здесь div не нужен:
https://github.com/WEVI0Z/Technomart/blob/4c55a382833acc1ff0d34eeef0801721fdd4dd30/catalog.html#L377-L379

**Comment by WEVI0Z** [comment]
Там исправил, но у меня вопрос, вот есть такой кусок кода, по-моему здесь этот див тоже избыточен, но я насчет него не уверен, можете подсказать?
![image](https://user-images.githubusercontent.com/43513627/116050928-b35a5b00-a680-11eb-970a-eacabddd2730.png)

**Comment by Morfey216** [comment]
> вот есть такой кусок кода, по-моему здесь этот див тоже избыточен

По сути да, однако я эту часть кода пока не трогаю: она будет подробно рассматриваться позже...

Где href у ссылки?
https://github.com/WEVI0Z/Technomart/blob/9dbd916f772970c93ab3fb06fb40f600c8c0e78b/catalog.html#L379-L381

**Comment by WEVI0Z** [comment]
Ссылку исправил в другом issue.
Там дивы сейчас тогда уберу
