### ISSUE TITLE
Странности классов

### ISSUE THREAD

**Issue by Morfey216** [WEVI0Z/Technomart#22]
Думаю, где-то здесь опечатка:
https://github.com/WEVI0Z/Technomart/blob/4c55a382833acc1ff0d34eeef0801721fdd4dd30/catalog.html#L23
https://github.com/WEVI0Z/Technomart/blob/4c55a382833acc1ff0d34eeef0801721fdd4dd30/index.html#L23

**Comment by WEVI0Z** [comment]
Опечатку исправил
