### ISSUE TITLE
Грубые ошибки в разметке

### ISSUE THREAD

**Issue by Morfey216** [WEVI0Z/Technomart#24]
Ссылки должны быть обозначены ссылками ))
https://github.com/WEVI0Z/Technomart/blob/4c55a382833acc1ff0d34eeef0801721fdd4dd30/index.html#L285

Да, конечно, сейчас при клике будет вызываться модальное окно и тег button для этого вполне подходит. Однако при отключении JavaScript кнопка работать перестанет, а ссылка могла бы вести на дополнительную страницу с формой... Так что это ссылка...

**Comment by WEVI0Z** [comment]
Я написал вам в Вк насчет этого, именно этот случай исправил, проверил остальные кнопки на странице, они вроде правильно названы, то есть они кнопками и являются

**Comment by Morfey216** [comment]
А где `href` ?
https://github.com/WEVI0Z/Technomart/blob/9dbd916f772970c93ab3fb06fb40f600c8c0e78b/index.html#L285

**Comment by WEVI0Z** [comment]
Боже, я идиот, я с помощью vs code просто заменил все пустые ссылки на ссылки с href, но не учел, что там внутри может быть что-то кроме href и вбивал в поиск тупо пустую ссылку. Думал, что будет быстрее чем вручную просматривать каждый тег, а в итоге пропустил кучу ошибок. Сейчас все пересмотрю

**Comment by WEVI0Z** [comment]
Все, перепроверил несколько раз, теперь все должно точно быть поменяно
