### ISSUE TITLE
type в форме

### ISSUE THREAD

**Issue by Morfey216** [WEVI0Z/Technomart#25]
Неправильный type
https://github.com/WEVI0Z/Technomart/blob/9dbd916f772970c93ab3fb06fb40f600c8c0e78b/index.html#L357

http://htmlbook.ru/html/input/type

**Comment by WEVI0Z** [comment]
Этот исправил, посмотрел остальные инпуты, там только текст поиска, имя пользователя и текст письма. То есть вроде как это все текст. Остальные инпуты относятся к выбору товара, там все на своих местах стоит
