### ISSUE TITLE
Декоративные изображения

### ISSUE THREAD

**Issue by Morfey216** [WEVI0Z/Technomart#3]
В разметку добавляются только контентные изображения, декоративные добавляются при помощи стилизации.

Подобных изображений в разметке быть не должно:
https://github.com/WEVI0Z/Technomart/blob/175f1f01561b939baba2b8a8a28e681c03e3b2f6/index.html#L25
https://github.com/WEVI0Z/Technomart/blob/175f1f01561b939baba2b8a8a28e681c03e3b2f6/index.html#L29
https://github.com/WEVI0Z/Technomart/blob/175f1f01561b939baba2b8a8a28e681c03e3b2f6/index.html#L104

Почитать можно здесь: https://htmlacademy.ru/blog/education/all/content-or-decor-img

**Comment by WEVI0Z** [comment]
Убрал все (мог что-то пропустить) декоративные изображения.
