### ISSUE TITLE
Избыточные теги

### ISSUE THREAD

**Issue by Morfey216** [WEVI0Z/Technomart#5]
Избегаем лишних тегов и оберток. Уверен, div здесь не нужен
https://github.com/WEVI0Z/Technomart/blob/175f1f01561b939baba2b8a8a28e681c03e3b2f6/index.html#L15-L19

**Comment by WEVI0Z** [comment]
Нашел, кроме этого div, еще пару span-ов лишних. Мог, что-то не заметить, но даже если я что-то пропустил, то, мне кажется, это все равно вскроется при стилизации

**Comment by Morfey216** [comment]
При стилизации обычно вскрываются недостающие, а вот избыточные не факт

**Comment by WEVI0Z** [comment]
Ну я сейчас еще раз проверил и когда другие ошибки правил, тоже посматривал, я только заметил пару элементов, где я сомневаюсь в их надобности, но мне кажется, что все-таки она там нужны
