### ISSUE TITLE
Разметка изменяемых данных

### ISSUE THREAD

**Issue by Morfey216** [WEVI0Z/Technomart#6]
https://github.com/WEVI0Z/Technomart/blob/175f1f01561b939baba2b8a8a28e681c03e3b2f6/index.html#L24-L27

Подобные вещи правильно размечать так:

`<a href="#">Закладки: <span>0</span></a>`

То есть, в span оборачиваем только число, что даст в последствии возможность изменять его значение через скрипты

**Comment by WEVI0Z** [comment]
Изменил Закладки и Корзину так, как вы написали
