### ISSUE TITLE
Навигация по сайту

### ISSUE THREAD

**Issue by Morfey216** [WEVI0Z/Technomart#7]
В тег nav оборачиваем только элементы главного меню. Контактная информация и управление личным кабинетом к навигации по сайту не относится
https://github.com/WEVI0Z/Technomart/blob/175f1f01561b939baba2b8a8a28e681c03e3b2f6/index.html#L41-L61

**Comment by WEVI0Z** [comment]
Вытащил из nav контактную информацию и управление личным кабинетом

**Comment by Morfey216** [comment]
Уже лучше. Однако зачем здесь оставил?
https://github.com/WEVI0Z/Technomart/blob/7586ca2cd0137db33dc7154a863dfa80c4418ded/index.html#L132-L135

И этот заголовок тоже не нужен
https://github.com/WEVI0Z/Technomart/blob/7586ca2cd0137db33dc7154a863dfa80c4418ded/index.html#L58

**Comment by WEVI0Z** [comment]
Удалил

**Comment by Morfey216** [comment]
А здесь?
https://github.com/WEVI0Z/Technomart/blob/b1b9e77e58e0b2bd6fe1cd56992f068d31ebcd92/catalog.html#L83

**Comment by WEVI0Z** [comment]
Тоже удалил

**Comment by Morfey216** [comment]
В шапке сайта контактную информацию и вспомогательные ссылки из навигации вынесли, а в футере ты упорно оставляешь... Согласись - странная логика...
https://github.com/WEVI0Z/Technomart/blob/2b2385f374a04f194d024a38a4d8e54dd440a2e6/index.html#L336-L357

**Comment by WEVI0Z** [comment]
Соглашусь. Убрал
