### ISSUE TITLE
Разметка ссылок на телефон и почту

### ISSUE THREAD

**Issue by Morfey216** [WEVI0Z/Technomart#8]
Во-первых - это ссылка!
https://github.com/WEVI0Z/Technomart/blob/175f1f01561b939baba2b8a8a28e681c03e3b2f6/index.html#L47

Во-вторых, ссылки на телефон и почту размечаются особым образом. Читать здесь https://developer.mozilla.org/ru/docs/Web/HTML/Element/A
В разделе ПРИМЕРЫ указаны правильные варианты

**Comment by WEVI0Z** [comment]
Исправил номера в header-e и footer-е

**Comment by Morfey216** [comment]
Не, не исправил:
https://github.com/WEVI0Z/Technomart/blob/7586ca2cd0137db33dc7154a863dfa80c4418ded/index.html#L411-L418

1. Это ссылки
https://github.com/WEVI0Z/Technomart/blob/7586ca2cd0137db33dc7154a863dfa80c4418ded/index.html#L413
https://github.com/WEVI0Z/Technomart/blob/7586ca2cd0137db33dc7154a863dfa80c4418ded/index.html#L417
И первая из них - ссылка на почту

2. Тег br там не нужен, фразы "Обратная связь" и "Разработано" оборачиваются в span-ы и всё нормально стилизуется

3. В значении атрибута href в номере телефона скобки не прописываем
https://github.com/WEVI0Z/Technomart/blob/7586ca2cd0137db33dc7154a863dfa80c4418ded/index.html#L384

**Comment by WEVI0Z** [comment]
Исправил в 2-х коммитах

**Comment by Morfey216** [comment]
Нет, так не пойдет:
https://github.com/WEVI0Z/Technomart/blob/b1b9e77e58e0b2bd6fe1cd56992f068d31ebcd92/index.html#L402

Ссылка на почту размечается так:
`<a href="mailto:mail@htmlacademy.ru">mail@htmlacademy.ru</a>`
Ты либо невнимательно смотришь документацию, либо ее игнорируешь... Скрин, сделанный по ссылке, которую я дал в первом комментарии: http://joxi.ru/DmBObWLs41NDk2

**Comment by WEVI0Z** [comment]
Да, моя ошибка, не так для себя истолковал значение этого mailto. Теперь все исправил
