### ISSUE TITLE
Избыточные элементы

### ISSUE THREAD

**Issue by Morfey216** [WEVI0Z/Technomart#9]
https://github.com/WEVI0Z/Technomart/blob/175f1f01561b939baba2b8a8a28e681c03e3b2f6/index.html#L45
https://github.com/WEVI0Z/Technomart/blob/175f1f01561b939baba2b8a8a28e681c03e3b2f6/index.html#L50
Что-то я не наблюдаю этих заголовков в макете: http://joxi.ru/Dr85J0yfMplgJm
С точки зрения доступности они здесь тоже не нужны

**Comment by WEVI0Z** [comment]
Убрал избыточные

**Comment by Morfey216** [comment]
https://github.com/WEVI0Z/Technomart/issues/7#issuecomment-742156217

**Comment by WEVI0Z** [comment]
Убрал в коммите с навигацией по сайту
